### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by masciugo** [yuco91/codice-fiscale#2]
```
$ node -v
v8.9.1
$ node
> var cf = require('codice-fiscale')
undefined
> cf
{ calcola: [Function: calcolaCodice] }
> var mycf = cf("mario", "rossi", "m", new Date('1980-1-1'), "udine")
TypeError: cf is not a function
    at repl:1:12
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:441:10)
    at emitOne (events.js:121:20)
    at REPLServer.emit (events.js:211:7)
    at REPLServer.Interface._onLine (readline.js:282:10)
    at REPLServer.Interface._line (readline.js:631:8)
>
```

**Comment by albertobasaglia** [comment]
Use 
```javascript
cf.calcola("mario", "rossi", "m", new Date('1980-1-1'), "udine")
```
 instead of 
```javascript
cf("mario", "rossi", "m", new Date('1980-1-1'), "udine")
```

**Comment by masciugo** [comment]
ok thanks.. but I had to look into the code to find the right usage which is completely different from the one showed in the readme:

```
> cf.calcola("mario", "rossi", "m", 26, 05, 77, "napoli")
'RSSMRA77E26F839A'
```
